import { Company, Role, Talent, Roadmap, RoadmapStep, TalentProgress } from './types';

export const mockCompanies: Company[] = [
  {
    id: '1',
    name: 'TechVision Inc',
    industry: 'Technology',
    description: 'Leading software development company specializing in AI and cloud solutions',
    website: 'https://techvision.com',
    location: 'San Francisco, CA',
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Global Finance Co',
    industry: 'Finance',
    description: 'International financial services provider with focus on digital banking',
    website: 'https://globalfinance.com',
    location: 'New York, NY',
    createdAt: '2024-02-20',
  },
  {
    id: '3',
    name: 'HealthTech Solutions',
    industry: 'Healthcare',
    description: 'Innovative healthcare technology for patient care and hospital management',
    website: 'https://healthtech.com',
    location: 'Boston, MA',
    createdAt: '2024-03-10',
  },
];

export const mockRoles: Role[] = [
  {
    id: '1',
    companyId: '1',
    title: 'Frontend Developer',
    department: 'Engineering',
    description: 'Build beautiful and responsive user interfaces using React and modern web technologies',
    level: 'Mid-Level',
    createdAt: '2024-01-20',
  },
  {
    id: '2',
    companyId: '1',
    title: 'Senior Backend Engineer',
    department: 'Engineering',
    description: 'Design and implement scalable backend systems and APIs',
    level: 'Senior',
    createdAt: '2024-01-22',
  },
  {
    id: '3',
    companyId: '2',
    title: 'Customer Support Specialist',
    department: 'Support',
    description: 'Provide exceptional customer service and resolve client inquiries',
    level: 'Junior',
    createdAt: '2024-02-25',
  },
  {
    id: '4',
    companyId: '3',
    title: 'Product Manager',
    department: 'Product',
    description: 'Lead product strategy and coordinate with cross-functional teams',
    level: 'Lead',
    createdAt: '2024-03-15',
  },
];

export const mockTalent: Talent[] = [
  {
    id: '1',
    name: 'Sarah Kimani',
    email: 'sarah.kimani@example.com',
    companyId: '1',
    roleId: '1',
    startDate: '2024-04-01',
    status: 'Active',
    progress: 65,
  },
  {
    id: '2',
    name: 'James Omondi',
    email: 'james.omondi@example.com',
    companyId: '1',
    roleId: '2',
    startDate: '2024-04-05',
    status: 'Active',
    progress: 42,
  },
  {
    id: '3',
    name: 'Grace Wanjiru',
    email: 'grace.wanjiru@example.com',
    companyId: '2',
    roleId: '3',
    startDate: '2024-04-10',
    status: 'Pending',
    progress: 15,
  },
  {
    id: '4',
    name: 'David Mwangi',
    email: 'david.mwangi@example.com',
    companyId: '3',
    roleId: '4',
    startDate: '2024-03-20',
    status: 'Completed',
    progress: 100,
  },
  {
    id: '5',
    name: 'Mary Achieng',
    email: 'mary.achieng@example.com',
    companyId: '1',
    roleId: '1',
    startDate: '2024-04-08',
    status: 'Active',
    progress: 88,
  },
];

const frontendRoadmapSteps: RoadmapStep[] = [
  {
    id: 's1',
    title: 'Welcome & Company Culture',
    description: 'Learn about TechVision\'s mission, values, and work culture',
    type: 'Video',
    duration: 30,
    content: 'Welcome to TechVision! In this session, you\'ll discover our company culture, core values, and what makes us unique.',
    aiAssistantEnabled: true,
    order: 1,
  },
  {
    id: 's2',
    title: 'Development Environment Setup',
    description: 'Set up your local development environment with required tools',
    type: 'Task',
    duration: 120,
    content: 'Follow the step-by-step guide to install Node.js, VS Code, Git, and configure your development environment.',
    resources: [
      { id: 'r1', title: 'Setup Guide', type: 'Document', url: '#' },
      { id: 'r2', title: 'VS Code Extensions', type: 'Link', url: '#' },
    ],
    aiAssistantEnabled: true,
    order: 2,
  },
  {
    id: 's3',
    title: 'React Fundamentals Review',
    description: 'Refresh your knowledge of React concepts and best practices',
    type: 'Reading',
    duration: 90,
    content: 'Review React hooks, component lifecycle, state management, and modern patterns used in our codebase.',
    aiAssistantEnabled: true,
    order: 3,
  },
  {
    id: 's4',
    title: 'Codebase Walkthrough',
    description: 'Explore our frontend architecture and key components',
    type: 'Video',
    duration: 60,
    content: 'Take a guided tour through our codebase structure, naming conventions, and architectural decisions.',
    aiAssistantEnabled: true,
    order: 4,
  },
  {
    id: 's5',
    title: 'Your First Component',
    description: 'Build and submit your first component for code review',
    type: 'Task',
    duration: 180,
    content: 'Create a reusable Button component following our design system and submit a pull request.',
    aiAssistantEnabled: true,
    order: 5,
  },
  {
    id: 's6',
    title: 'Code Review Simulator',
    description: 'Practice giving and receiving constructive code feedback',
    type: 'Simulator',
    duration: 45,
    content: 'Experience realistic code review scenarios and learn our feedback culture.',
    aiAssistantEnabled: true,
    order: 6,
  },
  {
    id: 's7',
    title: 'Team Introduction Meeting',
    description: 'Meet your team members and stakeholders',
    type: 'Meeting',
    duration: 60,
    content: 'Join a video call to meet your teammates and learn about ongoing projects.',
    aiAssistantEnabled: false,
    order: 7,
  },
  {
    id: 's8',
    title: 'Knowledge Check Quiz',
    description: 'Test your understanding of our tech stack and processes',
    type: 'Quiz',
    duration: 30,
    content: 'Complete a quiz covering React, TypeScript, and our development workflow.',
    aiAssistantEnabled: false,
    order: 8,
  },
];

export const mockRoadmaps: Roadmap[] = [
  {
    id: '1',
    companyId: '1',
    roleId: '1',
    title: 'Frontend Developer Onboarding',
    description: 'Comprehensive onboarding roadmap for new frontend developers at TechVision',
    steps: frontendRoadmapSteps,
    estimatedDuration: 14,
    createdAt: '2024-01-25',
  },
  {
    id: '2',
    companyId: '1',
    roleId: '2',
    title: 'Backend Engineer Onboarding',
    description: 'Complete onboarding journey for backend engineers',
    steps: [
      {
        id: 'b1',
        title: 'Welcome & Company Overview',
        description: 'Introduction to TechVision and engineering culture',
        type: 'Video',
        duration: 30,
        content: 'Welcome to the backend engineering team!',
        aiAssistantEnabled: true,
        order: 1,
      },
      {
        id: 'b2',
        title: 'Backend Architecture Overview',
        description: 'Understanding our microservices architecture',
        type: 'Reading',
        duration: 60,
        content: 'Learn about our distributed systems and service architecture.',
        aiAssistantEnabled: true,
        order: 2,
      },
    ],
    estimatedDuration: 21,
    createdAt: '2024-01-25',
  },
];

export const mockTalentProgress: TalentProgress[] = [
  {
    id: '1',
    talentId: '1',
    roadmapId: '1',
    completedSteps: ['s1', 's2', 's3', 's4', 's5'],
    currentStepId: 's6',
    startedAt: '2024-04-01',
    lastActivityAt: '2024-04-07',
    overallProgress: 65,
  },
  {
    id: '2',
    talentId: '2',
    roadmapId: '2',
    completedSteps: ['b1'],
    currentStepId: 'b2',
    startedAt: '2024-04-05',
    lastActivityAt: '2024-04-06',
    overallProgress: 42,
  },
];

// Helper functions
export const getCompanyById = (id: string) => mockCompanies.find(c => c.id === id);
export const getRoleById = (id: string) => mockRoles.find(r => r.id === id);
export const getTalentById = (id: string) => mockTalent.find(t => t.id === id);
export const getRoadmapByRoleId = (roleId: string) => mockRoadmaps.find(r => r.roleId === roleId);
export const getTalentProgress = (talentId: string) => mockTalentProgress.find(p => p.talentId === talentId);
